[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/wserr/adventofcode-2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
